services:
  web:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    env_file:
      - ./WebApplication1/.dev.env
    ports:
      - "5008:80"
      - "7024:443"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${HOME}/.aspnet/https:/https:ro
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys
      - ./WebApplication1/wwwroot/uploads:/app/wwwroot/uploads
    logging:
      driver: "json-file"

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: net9playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/18/data
    logging:
      driver: "json-file"

volumes:
  pgdata:
  dataprotection-keys:
    driver: local