services:
  web:
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=net9playground;Username=postgres;Password=yourpassword
    volumes:
      - ./WebApplication1:/src

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: net9playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: