services:
  web:
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=net9playground;Username=postgres;Password=yourpassword
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: net9playground
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: